<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" IncludeAssets="compile" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
    <Reference Include="gui_framework" HintPath="$(ValheimManagedDir)/gui_framework.dll" />
    <Reference Include="assembly_valheim" HintPath="$(ValheimManagedDir)/assembly_valheim.dll" />
    <Publicize Include="assembly_valheim" />
    <Reference Include="assembly_utils" HintPath="$(ValheimManagedDir)/assembly_utils.dll" />
    <Reference Include="UnityEngine" HintPath="$(ValheimManagedDir)/UnityEngine.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(ValheimManagedDir)/UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(ValheimManagedDir)/UnityEngine.UIModule.dll" />
    <Reference Include="UnityEngine.UI" HintPath="$(ValheimManagedDir)/UnityEngine.UI.dll" />
    <Reference Include="gui_framework" HintPath="$(ValheimManagedDir)/gui_framework.dll" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(ValheimManagedDir)/UnityEngine.InputLegacyModule.dll" />
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(ValheimManagedDir)/UnityEngine.ImageConversionModule.dll" />
    <Reference Include="BepInEx" HintPath="$(BepInExCoreDir)/BepInEx.dll" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(ValheimManagedDir)/Unity.TextMeshPro.dll" />
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(ValheimManagedDir)/UnityEngine.UnityWebRequestModule.dll" />
    <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(ValheimManagedDir)/UnityEngine.JSONSerializeModule.dll" />
    <Reference Include="0Harmony" HintPath="$(BepInExCoreDir)/0Harmony.dll" />
  </ItemGroup>
</Project>
